### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by luisFilipePT** [luisFilipePT/github-covid-finder#20]
This is an open issue!

Add overall design improvements like:

- Create a logo
- Fonts
- Colors
- Sizes

PR's welcome and if valuable even if not merged will be tagged with `hacktoberfest-accepted`!

**Comment by hansfelix** [comment]
I want to help you. I'll send a PR.

**Comment by lucid-dreem** [comment]
I'd be happy to help create a logo... are there any guidelines or rough ideas to work around?

**Comment by adyasha9** [comment]
I want to help.

**Comment by luisFilipePT** [comment]
> I'd be happy to help create a logo... are there any guidelines or rough ideas to work around?

Thanks, dark with at least a bit of red :) other than that shoot

**Comment by luisFilipePT** [comment]
@all-contributors please add @hansfelix for code and design
