### ISSUE TITLE
Add light/dark mode

### ISSUE THREAD

**Issue by luisFilipePT** [luisFilipePT/github-covid-finder#24]
* Toggle can be placed on the navbar
* Color Scheme can be improved

**Comment by Manas502** [comment]
I would love to contribute :)

**Comment by urmauur** [comment]
@luisFilipePT I'm working on it 👌🏻

**Comment by luisFilipePT** [comment]
@Manas502 thanks, since @urmauur  is already working on it maybe you guys can align?

**Comment by urmauur** [comment]
@luisFilipePT PR added ✌🏻

**Comment by luisFilipePT** [comment]
@urmauur thanks 🙌

**Comment by urmauur** [comment]
@luisFilipePT can you add this pr with `hacktoberfest-accepted`
