### ISSUE TITLE
Replace language string by logo

### ISSUE THREAD

**Issue by luisFilipePT** [luisFilipePT/github-covid-finder#27]
Right now some long strings in the language field break a bit the cards would be nice to display the logo instead.

![image](https://user-images.githubusercontent.com/9373787/95269275-fbbf4200-0830-11eb-9dc8-bdcd8d6465f9.png)

![image](https://user-images.githubusercontent.com/9373787/95269300-0a0d5e00-0831-11eb-97d6-e88bd5ef2284.png)

For those where that's not possible, if any, we would keep the string.

Bonus point 😄  add tooltip to the logo and open issues fields since they might not be that obvious

**Comment by tullur** [comment]
Hey, I'll fix this.

**Comment by aj-ya** [comment]
hey, I'll try to fix this.
