### ISSUE TITLE
Floating Text

### ISSUE THREAD

**Issue by urmauur** [luisFilipePT/github-covid-finder#41]
Found issue floating text @luisFilipePT feel free to assign me

![Screen Shot 2020-10-13 at 09 29 50](https://user-images.githubusercontent.com/10354610/95808498-bf12af80-0d36-11eb-91b5-d1a9de98301f.png)

**Comment by luisFilipePT** [comment]
Thanks for reporting 🙏 

@urmauur feel free to take it 😄.

**Comment by urmauur** [comment]
> Thanks for reporting 🙏
> 
> @urmauur feel free to take it 😄.

I take this one 👌🏻
